FROM alpine:3.18
RUN apk add --update make \
                     git \
                     neovim \
                     neovim-doc \
                     nodejs \
                     npm

CMD "nvim"
